### Extract transactions from multiple PDF files
@baseUrl = http://localhost:8000

# @name extractMultiple
POST {{baseUrl}}/extract
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="files"; filename="desjardins.pdf"
Content-Type: application/pdf

< ./desjardins.pdf
------WebKitFormBoundary
Content-Disposition: form-data; name="files"; filename="scotiabank.pdf"
Content-Type: application/pdf

< ./scotiabank.pdf
------WebKitFormBoundary
Content-Disposition: form-data; name="options"
Content-Type: application/json

{"format": "csv"}

------WebKitFormBoundary--